### ISSUE TITLE
Having issues running web app

### ISSUE THREAD

**Issue by dixonbegay** [CntoDev/CNTR#4]
node version: `v6.11.4`
OS: `Windows Server 2012 r2`

I install dependencies first
```
npm install
```
I run...
```
npm run prod:build
```
this displays in the console and that's it
```
> cntr-player@0.11.2 build:prod C:\wamp64\www\cntr-web
> rollup -c config/rollup.prod.config.js
```
tried to run...
```
npm run build
```
and got this in console
```
> cntr-player@0.11.2 build C:\wamp64\www\cntr-web
> rollup -c config/rollup.dev.config.js
```
There is no indication that the web app has started.

**Comment by lastmikoi** [comment]
CNTR doesn't provide for a way to start the web app using Node's development server, though I certainly see how it could prove useful.
CNTR, once built, should work with any web server able to distribute static files. As such for you to get started I'd recommend setting up a web server on your machine, configured to serve the built static files.

Glad to see our tool being used in the field ! Stay tuned for the upcoming release that will dramatically increase third-party usability as well as review the installation documentation. Feel free to provide further feedback on the current version however 👍

**Comment by dixonbegay** [comment]
Yeah just realized that. I saw the `index.html` and thought, oh just serve the `index.html` and `build/index.js` lol. Thanks for the help and quick response.

**Comment by dixonbegay** [comment]
Closing...
