### ISSUE TITLE
Function is spelled wrong and breaking mod

### ISSUE THREAD

**Issue by dixonbegay** [CntoDev/CNTR#6]
**Server OS:** `Windows Server 2012 r2`

**Description:** CNTR isn't functioning because of a script error. See rpt files below for what the error is. It seems this [line](https://github.com/CntoDev/CNTR/blob/master/addon/cntr/functions/fn_addEntityEventHandlers.sqf#L35) needs be `_entity call cntr_fnc_removeEntityEventHandlers;`

**Steps to reproduce:** Run current mod version from master repo and you will get error.

**RPT File**
Here is entire [RPT file](https://pastebin.com/RGNmXFFe)
Here is portion that is spouting out error...
```
16:59:03 Error in expression < call cntr_fnc_writeEvent; _entity call fn_removeEntityEventHandlers;};};
16:59:03   Error position: <fn_removeEntityEventHandlers;};};
16:59:03   Error Undefined variable in expression: fn_removeentityeventhandlers
```

**Comment by CNTODachi** [comment]
Hello Dixon sorry this has been sat here for so long we will get on a fix for this as soon as possible.

**Comment by isakic** [comment]
The bug is fixed in develop and will be merged into master as soon as possible.
