### ISSUE TITLE
Inclusion of new maps for replay

### ISSUE THREAD

**Issue by Abuk007** [CntoDev/CNTR#9]
Please add support for newly added maps for CNTO:
@tembalan        - v1.2 http://www.armaholic.com/page.php?id=33623
@caribou         - v1.0 http://www.armaholic.com/page.php?id=22146
@laskovets          - v004 http://www.armaholic.com/page.php?id=32285
@bozcaada         - v1.21 http://www.armaholic.com/page.php?id=29580
@aliabad_region     - v1.2 http://www.armaholic.com/page.php?id=32733
@beketov          - v1.0 http://www.armaholic.com/page.php?id=31454

**Comment by CptBananaPeel** [comment]
I've made the maps, but havn't tested them.

**Comment by CptBananaPeel** [comment]
The maps have been uploaded by @dulabu. The issue can now be considered as closed.
